name: Jest
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup Node.js
        uses: actions/setup-node@latest
        with:
          node-version: "16"

      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@latest
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install required deps for action
      - name: Install Dependencies
        run: npm --prefix App install app

      # Finally, run our tests
      - name: Run the tests
        run:  npm --prefix App test app